kind: Job
apiVersion: batch/v1
metadata:
  name: keca-options
spec:
  template:
    spec:
      containers:
      - name: keca-options
        #image: 'tensorflow/tensorflow'
        image: 'faizanbashir/python-datascience'
        workingDir: /storage
        command: ["sh", "./keca_options_rl/keca-options.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
